services:
  - type: web
    name: plausible-analytics
    env: elixir
    rootDir: plausible
    buildCommand: mix setup && mix assets.deploy
    startCommand: mix phx.server
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY_BASE
        sync: false
      - key: BASE_URL
        sync: false
      - key: DISABLE_CLICKHOUSE
        sync: false
      - key: ADMIN_USER_EMAIL
        sync: false
      - key: ADMIN_USER_NAME
        sync: false
      - key: ADMIN_USER_PWD
        sync: false
